//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.29 at 10:23:46 AM EST 
//


package edu.rpi.cmt.timezones.model.aliases;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfTimezoneAliasInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfTimezoneAliasInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timezoneAliasInfo" type="{urn:ietf:params:xml:ns:timezone-service-aliases}TimezoneAliasInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfTimezoneAliasInfoType", propOrder = {
    "timezoneAliasInfo"
})
public class ArrayOfTimezoneAliasInfoType {

    protected List<TimezoneAliasInfoType> timezoneAliasInfo;

    /**
     * Gets the value of the timezoneAliasInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timezoneAliasInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimezoneAliasInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimezoneAliasInfoType }
     * 
     * 
     */
    public List<TimezoneAliasInfoType> getTimezoneAliasInfo() {
        if (timezoneAliasInfo == null) {
            timezoneAliasInfo = new ArrayList<TimezoneAliasInfoType>();
        }
        return this.timezoneAliasInfo;
    }

}
