//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.29 at 10:23:46 AM EST 
//


package edu.rpi.cmt.timezones.model.aliases;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         aliases for a single timezone.  
 *       
 * 
 * <p>Java class for TimezoneAliasInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimezoneAliasInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tzid" type="{urn:ietf:params:xml:ns:timezone-service}TzidType"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:timezone-service-aliases}aliases"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimezoneAliasInfoType", propOrder = {
    "tzid",
    "aliases"
})
public class TimezoneAliasInfoType {

    @XmlElement(required = true)
    protected String tzid;
    @XmlElement(required = true)
    protected ArrayOfAliasInfoType aliases;

    /**
     * Gets the value of the tzid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTzid() {
        return tzid;
    }

    /**
     * Sets the value of the tzid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTzid(String value) {
        this.tzid = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAliasInfoType }
     *     
     */
    public ArrayOfAliasInfoType getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAliasInfoType }
     *     
     */
    public void setAliases(ArrayOfAliasInfoType value) {
        this.aliases = value;
    }

}
