//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.29 at 10:23:46 AM EST 
//


package edu.rpi.cmt.timezones.model.aliases;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         aliases for listed timezones.  
 *       
 * 
 * <p>Java class for TimezonesAliasInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimezonesAliasInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dtstamp" type="{urn:ietf:params:xml:ns:timezone-service}DtstampType"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:timezone-service-aliases}timezoneAliasInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimezonesAliasInfoType", propOrder = {
    "dtstamp",
    "timezoneAliasInfo"
})
public class TimezonesAliasInfoType {

    @XmlElement(required = true)
    protected XMLGregorianCalendar dtstamp;
    @XmlElement(required = true)
    protected ArrayOfTimezoneAliasInfoType timezoneAliasInfo;

    /**
     * Gets the value of the dtstamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtstamp() {
        return dtstamp;
    }

    /**
     * Sets the value of the dtstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtstamp(XMLGregorianCalendar value) {
        this.dtstamp = value;
    }

    /**
     * Gets the value of the timezoneAliasInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTimezoneAliasInfoType }
     *     
     */
    public ArrayOfTimezoneAliasInfoType getTimezoneAliasInfo() {
        return timezoneAliasInfo;
    }

    /**
     * Sets the value of the timezoneAliasInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTimezoneAliasInfoType }
     *     
     */
    public void setTimezoneAliasInfo(ArrayOfTimezoneAliasInfoType value) {
        this.timezoneAliasInfo = value;
    }

}
