//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.29 at 10:23:46 AM EST
//

package org.bedework.util.timezones.model.aliases;

import org.bedework.util.misc.ToString;

import java.util.Date;

/**
 *
 *         Provides information about an alias.
 *
 *
 * <p>Java class for AliasInfoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AliasInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alias" type="{urn:ietf:params:xml:ns:timezone-service}AliasType"/>
 *         &lt;element name="last-modified" type="{urn:ietf:params:xml:ns:timezone-service}LastmodifiedType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public class AliasInfoType {
  protected String alias;
  protected Date lastModified;
  protected String description;
  protected String source;

  /**
   * Gets the value of the alias property.
   *
   * @return String alias
   *
   */
  public String getAlias() {
    return alias;
  }

  /**
   * Sets the value of the alias property.
   *
   * @param value
   *
   */
  public void setAlias(final String value) {
    alias = value;
  }

  /**
   * Gets the value of the lastModified property.
   *
   * @return Date object
   *
   */
  public Date getLastModified() {
    return lastModified;
  }

  /**
   * Sets the value of the lastModified property.
   *
   * @param value
   *     allowed object is
   *     {@link Date }
   *
   */
  public void setLastModified(final Date value) {
    lastModified = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setDescription(final String value) {
    description = value;
  }

  /**
   * Gets the value of the source property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getSource() {
    return source;
  }

  /**
   * Sets the value of the source property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setSource(final String value) {
    source = value;
  }

  @Override
  public String toString() {
    ToString ts = new ToString(this);

    ts.append("alias", getAlias());
    ts.append("lastModified", getLastModified());
    ts.append("description", getDescription());
    ts.append("source", getSource());

    return ts.toString();
  }
}
