//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.29 at 10:23:46 AM EST
//
package org.bedework.util.timezones.model.aliases;

import org.bedework.util.misc.ToString;

import java.util.Date;
import java.util.List;

/**
 *
 *         aliases for listed timezones.
 *
 *
 * <p>Java class for TimezonesAliasInfoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TimezonesAliasInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dtstamp" type="{urn:ietf:params:xml:ns:timezone-service}DtstampType"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:timezone-service-aliases}timezoneAliasInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public class TimezonesAliasInfoType {
  protected Date dtstamp;
  protected List<TimezoneAliasInfoType> timezoneAliasInfo;

  /**
   * Gets the value of the dtstamp property.
   *
   * @return
   *     possible object is
   *     {@link Date }
   *
   */
  public Date getDtstamp() {
    return dtstamp;
  }

  /**
   * Sets the value of the dtstamp property.
   *
   * @param value
   *     allowed object is
   *     {@link Date }
   *
   */
  public void setDtstamp(final Date value) {
    dtstamp = value;
  }

  /**
   * Gets the value of the timezoneAliasInfo property.
   *
   * @return link List<TimezoneAliasInfoType>
   *
   */
  public List<TimezoneAliasInfoType> getTimezoneAliasInfo() {
    return timezoneAliasInfo;
  }

  /**
   * Sets the value of the timezoneAliasInfo property.
   *
   * @param value List<TimezoneAliasInfoType>
   *
   */
  public void setTimezoneAliasInfo(final List<TimezoneAliasInfoType> value) {
    timezoneAliasInfo = value;
  }

  @Override
  public String toString() {
    ToString ts = new ToString(this);

    ts.append("dtstamp", getDtstamp());
    ts.append("timezoneAliasInfo", getTimezoneAliasInfo(), true);

    return ts.toString();
  }

}
