//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.29 at 10:23:46 AM EST
//
package org.bedework.util.timezones.model.aliases;

import org.bedework.util.misc.ToString;

import java.util.List;

/**
 *
 *         aliases for a single timezone.
 *
 *
 * <p>Java class for TimezoneAliasInfoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TimezoneAliasInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tzid" type="{urn:ietf:params:xml:ns:timezone-service}TzidType"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:timezone-service-aliases}aliases"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
public class TimezoneAliasInfoType {
  protected String tzid;
  protected List<AliasInfoType> aliases;

  /**
   * Gets the value of the tzid property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getTzid() {
    return tzid;
  }

  /**
   * Sets the value of the tzid property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setTzid(final String value) {
    tzid = value;
  }

  /**
   * Gets the value of the aliases property.
   *
   * @return List of AliasInfoType
   *
   */
  public List<AliasInfoType> getAliases() {
    return aliases;
  }

  /**
   * Sets the value of the aliases property.
   *
   * @param value List of AliasInfoType
   *
   */
  public void setAliases(final List<AliasInfoType> value) {
    aliases = value;
  }

  @Override
  public String toString() {
    ToString ts = new ToString(this);

    ts.append("tzid", getTzid());
    ts.append("aliases", getAliases(), true);

    return ts.toString();
  }
}
